#!/bin/bash
Taking input into the script:
echo "Welcome to ACADA Bank"
echo "Please Slot in your card"
echo "Please Enter your pin"
read num
echo The pin you entered is $num
echo "yes or no"
read num1
echo login successfully
